arm64/dts/bogota: fix camera overlay
Camera node 'camera_main_af_mtk' is duplicated, needs to
be removed, so it can be overlayed.

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
kernel-6.12/../kernel/kernel_device_modules-6.12/arch/arm64/boot/dts/mediatek/
    cust_mt6855_camera_v4l2.dtsi:83.39-87.4: ERROR (duplicate_label): /fragment@46/
    __overlay__/camera_main_af@72: Duplicate label 'camera_main_af_mtk' on
    /fragment@46/__overlay__/camera_main_af@72 and /fragment@17/__overlay__/
    camera_main_af@0c
ERROR: Input tree has errors, aborting (use -f to force output)
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Change-Id: Id9597955f23186e4677a796337786a0fc97feab9
Reviewed-on: https://gerrit.mot.com/3506525
SLTApproved: Slta Waiver
SME-Granted: SME Approvals Granted
Tested-by: Jira Key
Reviewed-by: Obi-Wan Kenobi
Reviewed-by: Xinmin Fu <fuxm1@motorola.com>
Submit-Approved: Gilberto Gambugge Neto <gambugge@motorola.com>